task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),
    path("accounts/", include("django.contrib.auth.urls")),

    path("__debug__/", include("debug_toolbar.urls")),

]

tasks/urls.py
from django.urls import path

from tasks.views import (index,
                         TaskListView,
                         WorkerListView,
                         TaskDetailView,
                         TaskCreateView,
                         TaskUpdateView,
                         TaskDeleteView,
                         WorkerDetailView,
                         WorkerDeleteView,
                         WorkerCreateView,
                         PositionListView,
                         PositionDetailView,
                         PositionCreateView,
                         PositionUpdateView,
                         TaskTypeListView,
                         TaskTypeDetailView,
                         TaskTypeCreateView,
                         TaskTypeUpdateView,
                         TagListView,
                         TagDetailView,
                         TagCreateView,
                         TagUpdateView,
                         TagDeleteView,
                         ProjectListView,
                         ProjectDetailView,
                         ProjectCreateView,
                         ProjectUpdateView,
                         ProjectDeleteView,
                         TeamListView,
                         TeamDetailView,
                         TeamUpdateView,
                         TeamDeleteView,
                         TeamCreateView,
                         PositionDeleteView,
                         TaskTypeDeleteView)

urlpatterns = [
    path("", index, name="index"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/update/<int:pk>", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/delete/<int:pk>", TaskDeleteView.as_view(), name="task-delete"),

    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),

    path("workers/delete/<int:pk>", WorkerDeleteView.as_view(), name="worker-delete"),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("positions/<int:pk>", PositionDetailView.as_view(), name="position-detail"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path("positions/update/<int:pk>", PositionUpdateView.as_view(), name="position-update"),
    path("positions/delete/<int:pk>", PositionDeleteView.as_view(), name="position-delete"),
    path("task_types/", TaskTypeListView.as_view(), name="task-type-list"),
    path("task_types/<int:pk>/", TaskTypeDetailView.as_view(), name="task-type-detail"),
    path("task_types/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path("task_types/update/<int:pk>/", TaskTypeUpdateView.as_view(), name="task-type-update"),
    path("task_types/delete/<int:pk>/", TaskTypeDeleteView.as_view(), name="task-type-delete"),

    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/<int:pk>/", TagDetailView.as_view(), name="tag-detail"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/update/<int:pk>/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/delete/<int:pk>/", TagDeleteView.as_view(), name="tag-delete"),
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("projects/create/", ProjectCreateView.as_view(), name="project-create"),
    path("projects/update/<int:pk>/", ProjectUpdateView.as_view(), name="project-update"),
    path("projects/delete/<int:pk>/", ProjectDeleteView.as_view(), name="project-delete"),
    path("teams/", TeamListView.as_view(), name="team-list"),
    path("teams/<int:pk>/", TeamDetailView.as_view(), name="team-detail"),
    path("teams/create/", TeamCreateView.as_view(), name="team-create"),
    path("teams/update/<int:pk>/", TeamUpdateView.as_view(), name="team-update"),
    path("teams/delete/<int:pk>/", TeamDeleteView.as_view(), name="team-delete"),

]

app_name = "tasks"

tasks/forms.py
from datetime import date
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.utils import timezone

from tasks.models import Task, Position, Worker, Tag


class TaskForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Task
        fields = '__all__'
        widgets = {
            "deadline": forms.DateInput(
                attrs={"type": "date"}),
        }

    def clean_deadline(self):
        return validate_deadline(self.cleaned_data["deadline"])


def validate_deadline(deadline):
    if deadline < timezone.now().date():
        raise forms.ValidationError("Deadline can not be in the past")
    return deadline


class WorkerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "position"
        )

    position = forms.ModelChoiceField(
        queryset=Position.objects.all(),
        widget=forms.RadioSelect
    )





class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "Search by name",
        })
    )


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "Search by username",
        })
    )


class PositionSearchForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "Search by name",
        })
    )

class TaskTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "Search by name",
        })
    )


class TagSearchForm(forms.Form):
    name = forms.CharField(
        max_length=50,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "Search by name",
        })
    )


class ProjectSearchForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "Search by name",
        })
    )


class TeamSearchForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "Search by name",
        })
    )

tasks/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from tasks.forms import (TaskForm,
                         WorkerCreationForm,
                         TaskSearchForm,
                         WorkerSearchForm,
                         PositionSearchForm,
                         TaskTypeSearchForm, TagSearchForm, ProjectSearchForm, TeamSearchForm)
from tasks.models import Task, Worker, Position, TaskType, Tag, Project, Team


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_tasks = Task.objects.count()
    num_workers = Worker.objects.count()
    num_projects = Project.objects.count()
    num_teams = Team.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_tasks": num_tasks,
        "num_workers": num_workers,
        "num_projects": num_projects,
        "num_teams": num_teams,
        "num_visits": num_visits + 1,
    }

    return render(request, "tasks/index.html", context=context)


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 9

    def get_queryset(self):
        queryset = Task.objects.prefetch_related("assignees")
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["name"] = name
        context["search_form"] = TaskSearchForm(
            initial={"name": name},
        )
        return context

class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:task-list")
    success_message = "Task successfully created"


class TaskUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:task-list")
    success_message = "Task successfully updated"


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:task-list")

    def post(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(request, "Task successfully deleted")
        return response

class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 9

    def get_queryset(self):
        queryset = Worker.objects.all()
        form = WorkerSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(username__icontains=form.cleaned_data["username"])
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["username"] = username
        context["search_form"] = WorkerSearchForm(
            initial={"username": username},
        )
        return context


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    template_name = "tasks/worker_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["incompleted_tasks"] = self.object.tasks.filter(is_completed=False)
        context["completed_tasks"] = self.object.tasks.filter(is_completed=True)
        return context



class WorkerCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm
    success_url = reverse_lazy("tasks:worker-list")
    success_message = "Worker successfully created"


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("tasks:worker-list")

    def post(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(request, "Worker successfully deleted")
        return response


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 9

    def get_queryset(self):
        queryset = Position.objects.all()
        form = PositionSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["name"] = name
        context["search_form"] = PositionSearchForm(
            initial={"name": name},
        )
        return context


class PositionDetailView(LoginRequiredMixin, generic.DetailView):
    model = Position


class PositionCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Position
    fields = ("name",)
    success_url = reverse_lazy("tasks:position-list")
    success_message = "Position successfully updated."


class PositionUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Position
    fields = ("name",)
    success_url = reverse_lazy("tasks:position-list")
    success_message = "Position successfully updated"


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("tasks:position-list")

    def post(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(request, "Position successfully deleted")
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["has_dependencies"] = self.object.workers.exists()
        return context


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    paginate_by = 9
    template_name = "tasks/task_type_list.html"
    context_object_name = "task_type_list"

    def get_queryset(self):
        queryset = TaskType.objects.all()
        form = TaskTypeSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["name"] = name
        context["search_form"] = TaskTypeSearchForm(
            initial={"name": name},
        )
        return context


class TaskTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = TaskType
    template_name = "tasks/task_type_detail.html"
    context_object_name = "task_type"


class TaskTypeCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = TaskType
    fields = ("name",)
    success_url = reverse_lazy("tasks:task-type-list")
    template_name = "tasks/task_type_form.html"
    context_object_name = "task_type"
    success_message = "Task type successfully created."



class TaskTypeUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = TaskType
    fields = ("name",)
    success_url = reverse_lazy("tasks:task-type-list")
    template_name = "tasks/task_type_form.html"
    context_object_name = "task_type"
    success_message = "Task type successfully updated."


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("tasks:task-type-list")
    template_name = "tasks/task_type_confirm_delete.html"
    context_object_name = "task_type"

    def post(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(request, "Task type successfully deleted")
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["has_dependencies"] = self.object.tasks.exists()
        return context


class TagListView(LoginRequiredMixin, generic.ListView):
    model = Tag
    paginate_by = 9

    def get_queryset(self):
        queryset = Tag.objects.all()
        form = TagSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["name"] = name
        context["search_form"] = TagSearchForm(
            initial={"name": name},
        )
        return context


class TagDetailView(LoginRequiredMixin, generic.DetailView):
    model = Tag


class TagCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Tag
    fields = ("name",)
    success_url = reverse_lazy("tasks:tag-list")
    success_message = "Tag successfully created."


class TagUpdateView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Tag
    fields = ("name",)
    success_url = reverse_lazy("tasks:tag-list")
    success_message = "Tag successfully updated."


class TagDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:tag-list")

templates/tasks/position_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% if position_list %}
    <h1> All positions
     <a href="{% url 'tasks:position-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
    </h1>

    <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-primary" type="submit" value="Search">
    </form>

    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
      </tr>
      {% for position in position_list %}
        <tr>
          <td><a href="{% url 'tasks:position-detail' pk=position.id %}">{{ position.name }}</a></td>
          <td><a href="{% url 'tasks:position-update' pk=position.id %}">Update</a></td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no positions in task manager.</p>
  {% endif %}
{% endblock %}

templates/tasks/project_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} project</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/tasks/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag {{ tag.name }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">

    <a href="{% url 'tasks:tag-list' %}" class="btn btn-secondary">
      Cancel
    </a>

  </form>
{% endblock %}

templates/tasks/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% if tag_list %}
    <h1>All tags
     <a href="{% url 'tasks:tag-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>

    <form method="get" action="" class="form-inline">
      {{ search_form|crispy }}
      <input class="btn btn-primary" type="submit" value="Search">
    </form>

    <ul>
      {% for tag in tag_list %}
        <hr>
        <li><a href="{% url 'tasks:tag-detail' pk=tag.id %}">{{ tag.name }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    No tags in task manager yet.
  {% endif %}

{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/tasks/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% if task_list %}
    <h1> All tasks
     <a href="{% url 'tasks:task-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
    </h1>

    <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-primary" type="submit" value="Search">
    </form>

    <table class="table">
      <tr>
        <th>Name</th>
        <th>Deadline</th>
        <th>Is Completed</th>
        <th>Priority</th>
        <th>Type</th>
      </tr>
      {% for task in task_list %}
        <tr>
          <td><a href="{% url 'tasks:task-detail' pk=task.id %}">{{ task.name }}</a></td>
          <td>{{ task.deadline }}</td>
          <td>{{ task.is_completed }}</td>
          <td>{{ task.priority }}</td>
          <td>{{ task.task_type }}</td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no tasks in task manager.</p>
  {% endif %}
{% endblock %}

templates/tasks/task_type_detail.html
{% extends "base.html" %}

{% block content %}
  <h2>{{ task_type.task_count }} task{{ task_type.task_count|pluralize }}
    with task type {{ task_type.name }}
    <a href="{% url 'tasks:task-type-delete' pk=task_type.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>
  </h2>
  {% if task_type.task_count %}
    <ul>
      {% for task in task_type.tasks.all %}
        <hr>
        <li><a href="{% url 'tasks:task-detail' pk=task.id %}">{{ task.name }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    No tasks of this type yet.
  {% endif %}
{% endblock %}

templates/tasks/task_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% if task_type_list %}
    <h1> All task types
      <a href="{% url 'tasks:task-type-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>

    <form method="get" action="" class="form-inline">
      {{ search_form|crispy }}
      <input class="btn btn-primary" type="submit" value="Search">
    </form>

    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
      </tr>
      {% for task_type in task_type_list %}
        <tr>
          <td><a href="{% url 'tasks:task-type-detail' pk=task_type.id %}">{{ task_type.name }}</a></td>
          <td><a href="{% url 'tasks:task-type-update' pk=task_type.id %}">Update</a></td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no task types in task manager.</p>
  {% endif %}
{% endblock %}

templates/tasks/team_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete team {{ team.name }}?</h1>
  {% if has_dependencies %}
    <p class="text-danger">This item cannot be deleted. There are related objects depending on it.</p>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger"
           {% if has_dependencies %}disabled{% endif %}>

    <a href="{% url 'tasks:project-list' %}" class="btn btn-secondary">
      Cancel
    </a>

  </form>
{% endblock %}

templates/tasks/team_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} team</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/tasks/team_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% if team_list %}
    <h1> All teams
      <a href="{% url 'tasks:team-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>

    <form method="get" action="" class="form-inline">
      {{ search_form|crispy }}
      <input class="btn btn-primary" type="submit" value="Search">
    </form>

    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
      </tr>
      {% for team in team_list %}
        <tr>
          <td><a href="{% url 'tasks:team-detail' pk=team.id %}">{{ team.name }}</a></td>
          <td><a href="{% url 'tasks:team-update' pk=team.id %}">Update</a></td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no teams in task manager.</p>
  {% endif %}
{% endblock %}

templates/tasks/worker_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete worker?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">

    <a href="{% url 'tasks:worker-list' %}" class="btn btn-secondary">
      Cancel
    </a>
  </form>
{% endblock %}

templates/tasks/worker_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ worker.username }}
    <a href="{% url 'tasks:worker-delete' pk=worker.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>
  </h1>

  <p><strong>First name:</strong> {{ worker.first_name }}</p>
  <p><strong>Last name:</strong> {{ worker.last_name }}</p>
  <p><strong>Email:</strong> {{ worker.email }}</p>
  <p><strong>Is staff:</strong> {{ worker.is_staff }}</p>

  <div class="ml-3">
    <h4>Teams</h4>
    <ul>
      {% for team in worker.teams.all %}
        <hr>
        <li><a href="{% url 'tasks:team-detail' pk=team.id %}"> {{ team.name }} </a></li>
      {% empty %}
        <p>Worker does not have any team yet.</p>
      {% endfor %}
    </ul>

    <br>

    <h4>Uncompleted tasks</h4>

    {% for task in incompleted_tasks %}
      <hr>
      <p><strong>Name:</strong><a href="{% url 'tasks:task-detail' pk=task.id %}"> {{ task.name }} </a></p>
      <p><strong>Priority:</strong> {{ task.priority }}</p>
      <p><strong>Deadline:</strong> {{ task.deadline }}</p>
    {% empty %}
      <p>No incompleted tasks</p>
    {% endfor %}

    <h4>Completed tasks</h4>

    {% for task in completed_tasks %}
      <hr>
      <p><strong>Name:</strong><a href="{% url 'tasks:task-detail' pk=task.id %}"> {{ task.name }} </a></p>
      <p><strong>Priority:</strong> {{ task.priority }}</p>
      <p><strong>Deadline:</strong> {{ task.deadline }}</p>

    {% empty %}
      <p>No completed tasks</p>
    {% endfor %}
  </div>
{% endblock %}